TAO-7150 fix bug on overlap on right side of the page
oat-sa/popper.js pull request #1
Opened 2018-11-21 13:01 UTC by handleman

relate to https://github.com/oat-sa/tao-core/pull/1880

Fixed overlapping when reference element ( that triggers popup) is placed on  right edge of the page.
1. packages/popper/src/modifiers/arrow.js
2. packages/popper/src/modifiers/preventOverflow.js

fixed  overlap on word wrap of content that was dynamically added to tooltip content.
1) packages/tooltip/src/index.js

2018-11-23 09:02 UTC, krampstudio requested changes
A minor change on the style.

2018-11-23 09:02 UTC, krampstudio commented on packages/tooltip/src/index.js
> +    setTimeout(function () {
please keep the consistancy with their style : 
```
container.appendChild(tooltipNode);
setTimeout( () => this.show());
```

2018-11-26 09:58 UTC, handleman commented on packages/tooltip/src/index.js
> +    setTimeout(function () {
ready

2018-11-28 10:24 UTC, krampstudio approved these changes

2018-11-29 07:23 UTC, merged